name: Security Vulnerability Report
description: Report a security vulnerability in the Security Event Exporter
title: "[SECURITY] "
labels: ["security", "vulnerability"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report
        
        **Please do not report security vulnerabilities through public GitHub issues.**
        
        Instead, please report them via email to: [security@opentelemetry.io](mailto:security@opentelemetry.io)
        
        This template is for informational purposes only. For actual security reports, please use the email address above.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security vulnerability is this?
      options:
        - Authentication/Authorization
        - Input Validation
        - Injection Attack
        - Information Disclosure
        - Denial of Service
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Insecure Direct Object Reference
        - Security Misconfiguration
        - Using Components with Known Vulnerabilities
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the severity of this vulnerability?
      options:
        - Critical
        - High
        - Medium
        - Low
        - Informational
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the vulnerability
      placeholder: Describe the security vulnerability...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the vulnerability
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Describe the expected behavior...

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the actual behavior...

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: Describe the potential impact...

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: Do you have any suggestions for fixing this vulnerability?
      placeholder: Describe any suggested fixes or mitigations...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the vulnerability here
      placeholder: Add any additional context...

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this issue, you agree to the following terms
      options:
        - label: I understand that this is for informational purposes only and that actual security vulnerabilities should be reported via email to security@opentelemetry.io
          required: true
        - label: I understand that this issue may be closed without further action if it's not a security vulnerability
          required: true
